// 시연 프리셋: 저장소 결과를 브라우저에서 다시 보는 설정. DOM이 없어 main.js, check.html, Worker가 함께 읽는다.
// id는 주소 해시(#TP-0047)와 대시보드 링크가 쓴다. 한 TP에 프리셋이 여럿이면 #TP-XXXX는 첫 번째를 연다.
// automation/dashboard_links.py가 각 줄의 `{ id, tp, label` 앞부분을 정규식으로 읽는다. 새 필드는 label 뒤에 둔다.
//
// 필드: group 묶음(GROUPS 키), watch 볼 것, expect 이 페이지 결과(status·fail은 check.html이 판정한다),
// repo 저장소 결과, pair 비교 상대(주소 해시, 덮어쓰기 가능. 없으면 null),
// set defaultOptions() 덮어쓰기, layer 처음 고를 층, peds 시연 지형의 경로에 놓을 보행자 수.
// expect.fail은 sim.js의 failCode다(lethal, tipover, collision, timeout). 결과가 expect와 다르면 화면 배너에 쓴다.
export const GROUPS = { perception: "가림·인식", robot: "로봇·자세", terrain: "지형·차체", stack: "스택·보행자" };

export const PRESETS = [
  { id: "TP-0031-low", tp: "TP-0031", label: "가림, 센서 0.3 m", group: "perception",
    watch: "센서가 낮아 포트홀 바닥이 가려진다. 못 본 칸(검정)은 cost 0.5라 그대로 지나다 빠진다.",
    expect: { status: "failed", fail: "lethal", text: "5.0 s 치명 셀 진입" }, repo: "센서 0.3 m에서 6/10", pair: "TP-0031-high",
    set: { scenario: "bumps_potholes", level: 0, seed: 4, perception: "occlusion", sensorHeight: 0.3, shadowCeiling: false, depthPrior: false } },
  { id: "TP-0031-high", tp: "TP-0031", label: "센서 1.0 m로 올리기", group: "perception",
    watch: "센서를 1.0 m로 올리면 포트홀 바닥까지 보여 치명 셀(빨강)을 미리 돌아간다.",
    expect: { status: "reached", text: "도달 15.8 s" }, repo: "0.8 m 이상에서 9–10/10", pair: "TP-0031-low",
    set: { scenario: "bumps_potholes", level: 0, seed: 4, perception: "occlusion", sensorHeight: 1.0, shadowCeiling: false, depthPrior: false } },
  { id: "TP-0046", tp: "TP-0046", label: "가림 + 그림자 상한만", group: "perception",
    watch: "그림자 상한이 못 본 칸의 높이에 위 한계를 둔다(보라). 상한만으로는 포트홀을 치명으로 읽지 못한다.",
    expect: { status: "failed", fail: "lethal", text: "4.4 s 치명 셀 진입" }, repo: "36/40, 상한만으로는 그대로", pair: "TP-0047",
    set: { scenario: "bumps_potholes", level: 0, seed: 4, perception: "occlusion", shadowCeiling: true, depthPrior: false } },
  { id: "TP-0047", tp: "TP-0047", label: "+ 깊이 prior", group: "perception",
    watch: "상한이 둘레 지면보다 0.10 m 넘게 낮은 칸을 깊이 prior가 치명(자홍)으로 채워, 경로가 포트홀을 비켜 간다.",
    expect: { status: "reached", text: "도달 17.4 s" }, repo: "40/40", pair: "TP-0046",
    set: { scenario: "bumps_potholes", level: 0, seed: 4, perception: "occlusion", shadowCeiling: true, depthPrior: true, evidence: true } },
  { id: "TP-0048", tp: "TP-0048", label: "내림 턱 오탐(증거 제한 끔)", group: "perception",
    watch: "내림 턱 너머 못 본 칸을 깊이 prior가 치명으로 채워, 턱 앞에 치명 벽이 잠깐 선다(오탐).",
    expect: { status: "reached", text: "도달 13.0 s, 턱 앞에 보라 치명 벽이 잠깐 선다" }, repo: "오탐 9.1칸, 증거 제한으로 1.3칸(TP-0067)", pair: "TP-0048?ev=1",
    set: { scenario: "down_curb", level: 0, seed: 1, perception: "occlusion", shadowCeiling: true, depthPrior: true, evidence: false } },
  { id: "TP-0082", tp: "TP-0082", label: "차체 기준 층: 둔덕 경사", group: "terrain",
    watch: "차체 기하 기준 층. 둔덕 양옆 가파른 곳은 '자세로 못 들어감', 그 둘레는 '일부 방향만 막힘'이다.",
    expect: { status: "reached", text: "도달 13.8 s" }, repo: "RSL 필터의 MISS가 이 경사에 몰림", pair: null,
    set: { scenario: "slope_crossfall", level: 0, seed: 0, perception: "range" }, layer: "chassis" },
  { id: "TP-0100", tp: "TP-0100", label: "L1 간이: 못 본 칸이 위험", group: "perception",
    watch: "로봇이 본 높이 층. LiDAR 링 사이가 비어 있고, 범프에서 몸체가 기울어 앞 포트홀을 덜 본다.",
    expect: { status: "failed", fail: "lethal", text: "4.9 s 치명 셀 진입" }, repo: "L1 근거리 MISS 38.8%(L0 가림 17.2%)", pair: "TP-0100?un=1.5",
    set: { scenario: "bumps_potholes", level: 0, seed: 4, perception: "l1lite", shadowCeiling: true, depthPrior: true }, layer: "belief_elev" },
  { id: "TP-0101", tp: "TP-0101", label: "근거리 미관측을 치명으로(1.5 m)", group: "perception",
    watch: "로봇 1.5 m 안의 못 본 칸을 치명(짙은 빨강)으로 둔다. L0 가림에서는 그런 칸이 대개 포트홀 바닥이라 주행이 거의 같다.",
    expect: { status: "reached", text: "도달 17.4 s" }, repo: "도달 가능 근거리 MISS 2,204 → 0", pair: "TP-0101?un=0",
    set: { scenario: "bumps_potholes", level: 0, seed: 4, perception: "occlusion", shadowCeiling: true, depthPrior: true, unknownNear: 1.5 } },
  { id: "TP-0065", tp: "TP-0065", label: "L1 간이 + 전면 스테레오 + 미관측 1.5 m", group: "perception",
    watch: "전면 스테레오가 LiDAR 근거리 사각을 메운다. 근거리 미관측 1.5 m를 켜도 느려지지 않는다.",
    expect: { status: "reached", text: "도달 15.3 s(스테레오 없이 41.0 s)" }, repo: "L1 + 미관측 1.5 m의 평균 도달 18.7 s → 스테레오로 15.5 s", pair: "TP-0065?st=0",
    set: { scenario: "down_curb", level: 0, seed: 0, perception: "l1lite", shadowCeiling: true, depthPrior: true, stereo: true, unknownNear: 1.5 }, layer: "belief_elev" },
  { id: "TP-0102", tp: "TP-0102", label: "사족 보행 + L1 간이(자세 보상)", group: "robot",
    watch: "높이 오차 층. 매퍼가 몸체 자세를 알면 걸음새 흔들림 아래서도 오차가 1 cm대다.",
    expect: { status: "reached", text: "도달 17.6 s, 평균 높이 오차 1.6 cm" }, repo: "이 페이지 전용", pair: "TP-0102-nocomp",
    set: { robot: "quadruped", scenario: "bumps_potholes", level: 0, seed: 4, perception: "l1lite", sensorHeight: 0.45, poseComp: true }, layer: "elev_err" },
  { id: "TP-0102-nocomp", tp: "TP-0102", label: "사족: 자세 보상 끔", group: "robot",
    watch: "자세를 모르면 먼 링이 줄무늬로 틀린다. 그 오차가 턱으로 읽혀 앞을 막는다.",
    expect: { status: "failed", fail: "timeout", text: "60 s 시간 초과, 평균 높이 오차 2.9 cm" }, repo: "이 페이지 전용", pair: "TP-0102",
    set: { robot: "quadruped", scenario: "bumps_potholes", level: 0, seed: 4, perception: "l1lite", sensorHeight: 0.45, poseComp: false }, layer: "elev_err" },
  { id: "TP-0102-noise", tp: "TP-0102", label: "사족: 자세 추정 잡음 1°", group: "robot",
    watch: "자세 추정 잡음 1°. 높이 오차가 커져 거짓 치명이 늘고 도달이 늦어진다.",
    expect: { status: "reached", text: "도달 56.9 s(느려짐)" }, repo: "이 페이지 전용", pair: "TP-0102",
    set: { robot: "quadruped", scenario: "bumps_potholes", level: 0, seed: 4, perception: "l1lite", sensorHeight: 0.45, poseComp: true, poseNoise: 1 }, layer: "elev_err" },
  { id: "TP-0102-wheelleg", tp: "TP-0102", label: "바퀴 사족: 연석을 바로 오른다", group: "robot",
    watch: "바퀴 사족은 턱 한계가 15 cm라 경사로로 돌지 않고 연석을 바로 오른다.",
    expect: { status: "reached", text: "도달 15.5 s(스워브는 경사로로 35.3 s)" }, repo: "이 페이지 전용", pair: "TP-0102-wheelleg?rb=swerve&sh=0.3",
    set: { robot: "wheelLeg", scenario: "curb_ramp", level: 0, seed: 0, perception: "l1lite", sensorHeight: 0.45, poseComp: true }, layer: "elev_err" },
  { id: "TP-0039", tp: "TP-0039", label: "연석 L3 (경사로 1.1 m)", group: "terrain",
    watch: "난이도 레벨 3: 연석 0.24 m, 경사로 폭 1.1 m. 좁은 경사로를 찾아 오른다.",
    expect: { status: "reached", text: "도달 27.6 s" }, repo: "guidance+mppi 12/12", pair: null,
    set: { scenario: "curb_ramp", level: 3, seed: 0, perception: "range" } },
  { id: "planner-vs-controller", tp: "P/C", label: "Planner 없이 MPPI만", group: "stack",
    watch: "Planner를 직선으로 두면 MPPI 혼자서는 지형을 돌아가는 길을 찾지 못한다.",
    expect: { status: "failed", fail: "timeout", text: "60 s 시간 초과(Guidance면 14.8 s 도달)" }, repo: "Planner가 필요한 이유", pair: "planner-vs-controller?pl=guidance",
    set: { scenario: "bumps_potholes", level: 0, seed: 0, perception: "range", planner: "straight" } },
  { id: "TP-0027", tp: "TP-0027", label: "보행자 3명", group: "stack",
    watch: "경로 위 보행자 3명. 분홍 점이 4 s 예측이고, MPPI가 이것을 비용으로 피한다.",
    expect: { status: "reached", text: "도달 17.3 s" }, repo: "보행자 2명 조건 40/40, 충돌 0", pair: null,
    set: { scenario: "bumps_potholes", level: 0, seed: 1, perception: "range" }, peds: 3 },
];
